services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: "ChangeMe"
      MYSQL_DATABASE: "todoApp"
    ports:
      - "3306:3306"

  go:
    build: go
    ports:
      - "8090:8090"
    working_dir: /goApi
    environment:
      - HOME=/tmp
    command: go run main.go
    user: "${UID}:${GID}"
    userns_mode: host
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    volumes:
      - ../goApi:/goApi
    tmpfs:
      - /tmp:exec
    depends_on:
      - db

  sveltekit:
    build: node
    working_dir: /svelteApp
    command: pnpm run dev
    user: "${UID}:${GID}"
    userns_mode: host
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    volumes:
      - ../svelteApp:/svelteApp
      - ../.cache/node:/tmp/.cache/node
    tmpfs:
      - /tmp

  nginx:
    build:
      context: nginx
    ports:
      - "5173:5173"
    volumes:
      - ../:/app:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    tmpfs:
      - /tmp
    depends_on:
      - sveltekit